In [1]:
import numpy as np

# np.random.randn(d0, d1, ..., dn)

## If positive, int_like or int-convertible arguments are provided,`randn` generates an array of shape ``(d0, d1, ..., dn)``, filled with random floats sampled from a univariate "normal" (Gaussian) distribution of mean 0 and variance 1

In [2]:
np.random.randn()

0.2597387740687495

In [3]:
np.random.randn(2)

array([-1.39245977,  0.35800357])

In [4]:
np.random.randn(2,4)

array([[-0.16924331, -0.90554014, -0.10099863,  1.17608343],
       [-0.21301159, -0.64609153,  0.32744929, -0.10073608]])

In [5]:
np.random.randn(2, 4, 3)

array([[[ 0.42844633, -1.0180634 ,  0.67860865],
        [ 2.19330981, -0.98683502, -1.36772023],
        [-2.91080923,  0.50364079,  2.04126009],
        [ 0.74744364, -1.3948913 , -1.12946771]],

       [[ 0.39989695, -1.52852866,  0.32573374],
        [-0.42352182, -2.23891361,  0.67640831],
        [-0.87195323, -0.90579098, -2.33872666],
        [ 1.13312705, -2.08916739, -0.15865924]]])

# np.random.rand(d0, d1, ..., dn)

## Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0, 1)``.

In [6]:
np.random.rand()

0.4593660359885118

In [7]:
np.random.rand(2)

array([0.11971396, 0.33815952])

In [8]:
np.random.rand(2, 4)

array([[0.84356597, 0.93522903, 0.13619639, 0.55487292],
       [0.46957087, 0.39707767, 0.95355475, 0.45972223]])

In [9]:
np.random.rand(2, 4, 3)

array([[[0.4362857 , 0.3043142 , 0.62620898],
        [0.51830995, 0.4871273 , 0.09854218],
        [0.91392645, 0.10326172, 0.00147538],
        [0.8646809 , 0.42300312, 0.42200105]],

       [[0.63732476, 0.10951255, 0.52253948],
        [0.10818771, 0.40534108, 0.68885759],
        [0.81773613, 0.13996474, 0.71667191],
        [0.23980886, 0.23261864, 0.01889582]]])

# np.random.randint(low, high=None, size=None, dtype='l')

## Return random integers from the "discrete uniform" distribution of the specified dtype in the "half-open" interval [`low`, `high`). If `high` is None (the default), then results are from [0, `low`).

In [10]:
np.random.randint(2)

1

In [11]:
np.random.randint(2, 10)

7

In [12]:
np.random.randint(2, 10, (2, 3))

array([[5, 7, 2],
       [9, 9, 6]])

# np.random.random(size=None)

## Return random floats in the half-open interval [0.0, 1.0).

In [13]:
np.random.random()

0.9562370651731517

In [14]:
np.random.random((2, 3))

array([[0.88977554, 0.66980714, 0.28574057],
       [0.60787601, 0.38627526, 0.29151618]])

# np.random.uniform( low=0.0, high=1.0, size=None )

## Samples are uniformly distributed over the half-open interval ``[low, high)``

In [15]:
np.random.uniform()

0.6935815622222938

In [16]:
np.random.uniform(1.0, 2.0)

1.8460150510909448

In [17]:
np.random.uniform(1.0, 2.0, (2, 3))

array([[1.36550698, 1.70463993, 1.89196058],
       [1.47924355, 1.69908462, 1.31163491]])

# np.random.normal( loc=0.0, scale=1.0, size=None )

## loc : float or array_like of floats Mean ("centre") of the distribution.
## scale : float or array_like of floats Standard deviation (spread or "width") of the distribution.
## size : int or tuple of ints, optional

In [18]:
np.random.normal()

-2.493542886333145

In [19]:
np.random.normal(size=(2, 3))

array([[ 0.47596865, -1.11513258,  0.48201486],
       [ 0.89399978, -0.03305672, -0.1273946 ]])

In [20]:
import tensorflow as tf
sess = tf.InteractiveSession()

# tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)

In [21]:
sess.run( tf.random_normal(shape=(2, 3)) )

array([[ 0.2711758 ,  0.7746385 , -0.67552245],
       [-2.2267616 ,  1.4311455 , -0.62580645]], dtype=float32)

# tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

In [22]:
sess.run( tf.random_uniform(shape=(2, 3, 4), minval=1, maxval=10) )

array([[[6.9052415, 6.679331 , 8.127391 , 6.598106 ],
        [6.810748 , 8.081869 , 3.1663   , 1.3118529],
        [8.176683 , 5.29624  , 5.256803 , 4.923271 ]],

       [[1.7653705, 4.916602 , 8.580877 , 7.9148464],
        [1.8651433, 7.3495035, 8.921993 , 3.0041218],
        [5.637839 , 6.12631  , 3.4627109, 6.783294 ]]], dtype=float32)